name: CI/CD for SaaS Intelligence Agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run application check
        run: |
          echo "Starting Flask app in the background..."
          python agent/main.py &
          sleep 5 # Give the server a moment to start

          echo "Checking if the process is running..."
          pgrep -f "python agent/main.py" || (echo "Flask app failed to start" && exit 1)

          echo "Checking if the API endpoint is responding..."
          curl --fail -X POST http://127.0.0.1:5001/api/research || (echo "API endpoint not responding" && exit 1)

          echo "Test check successful!"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: sudo snap install heroku --classic

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
        env:
          # This is required to point to the subdirectory containing the app
          HD_APP_BASE: "."
          # This tells Heroku to deploy the root directory, not a subdirectory
          HD_PROCFILE: "Procfile"